In [7]:
import numpy as np
import matplotlib.pyplot as plt
import h5py

%matplotlib inline

In [8]:
A=np.array([[56.0,0.0,4.4,68.0],
            [1.2,104.0,52.0,8.0],
[1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [9]:
cal=A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [10]:
percentage=100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [15]:
a=np.random.randn(12288,150)
b=np.random.randn(150,45)
c=np.dot(a,b)
print(c)
c.shape

[[ -2.15317913  -1.8521329    0.66354238 ... -11.18909509  -6.13075496
  -11.13495218]
 [  9.55064623 -13.36966399  15.66799909 ...  -8.54979134 -21.8894469
  -21.49647548]
 [  3.89331687  -0.68086155  -5.60126166 ...  -2.83907816   6.62967767
   25.67488545]
 ...
 [ -9.03115404  -2.21259049 -10.32199707 ...  -9.93400354 -13.30746579
   10.48370282]
 [ -0.90186187  -3.5679763   12.56507168 ...  -3.32519252  -5.3998344
    6.86929421]
 [  9.12965304  -5.92750148  -3.15727939 ...  23.22077161 -24.00668336
  -12.8646017 ]]


(12288, 45)

In [16]:
d=a*b

ValueError: operands could not be broadcast together with shapes (12288,150) (150,45) 

In [30]:

a=np.random.randn(3,4) # 
print("a=",a)
b=np.random.randn(4,1) # 

print("b=",b)



for i in range(3):

 for j in range(4):
   c[i][j] = a[i][j]*b[j]
d=a*b.T
print(c)
print(d)

a= [[-0.02029678 -0.51649965 -0.08624824 -0.47910596]
 [ 0.58965554  0.15616696 -0.42541283 -0.43281476]
 [-0.01119614  0.32914629  0.14741442  0.10483495]]
b= [[-1.19601224]
 [-0.40062998]
 [ 0.17057945]
 [ 0.72085057]]
[[ 0.0242752   0.20692525 -0.01471218 -0.34536381]
 [-0.70523524 -0.06256517 -0.07256669 -0.31199477]
 [ 0.01339072 -0.13186587  0.02514587  0.07557033]]
[[ 0.0242752   0.20692525 -0.01471218 -0.34536381]
 [-0.70523524 -0.06256517 -0.07256669 -0.31199477]
 [ 0.01339072 -0.13186587  0.02514587  0.07557033]]


In [31]:

a=np.random.randn(4,3) # 

b=np.random.randn(3,2) # 


c=a∗b

SyntaxError: invalid character '∗' (U+2217) (3678481329.py, line 6)