In [7]:
import numpy as np

def conv2d(image, kernel, stride=1, padding=0):
    image_padded = np.pad(image, ((padding, padding), (padding, padding)), mode='constant', constant_values=0)
    kernel_height, kernel_width = kernel.shape
    image_height, image_width = image_padded.shape
    output_height = (image_height - kernel_height) // stride + 1
    output_width = (image_width - kernel_width) // stride + 1
    output = np.zeros((output_height, output_width))
    
    for i in range(0, output_height * stride, stride):
        for j in range(0, output_width * stride, stride):
            region = image_padded[i:i + kernel_height, j:j + kernel_width]
            output[i // stride, j // stride] = np.sum(region * kernel)
    
    return output

def relu(x):
    return np.maximum(0, x)

def max_pooling(image, size=2, stride=2):
    output_height = (image.shape[0] - size) // stride + 1
    output_width = (image.shape[1] - size) // stride + 1
    output = np.zeros((output_height, output_width))
    
    for i in range(0, output_height * stride, stride):
        for j in range(0, output_width * stride, stride):
            region = image[i:i + size, j:j + size]
            output[i // stride, j // stride] = np.max(region)
    
    return output

def fully_connected_layer(input_vector, weights, bias):
    return np.dot(input_vector, weights) + bias

# Example usage
if __name__ == "__main__":
    image = np.random.rand(5, 5)
    kernel = np.random.rand(3, 3)
    
    conv_output = conv2d(image, kernel)
    relu_output = relu(conv_output)
    pooled_output = max_pooling(relu_output)
    
    fc_weights = np.random.rand(pooled_output.size, 3)
    fc_bias = np.random.rand(3)
    fc_input = pooled_output.flatten()
    fc_output = fully_connected_layer(fc_input, fc_weights, fc_bias)
    
    print("Convolution Output:\n", conv_output)
    print("ReLU Output:\n", relu_output)
    print("Max Pooling Output:\n", pooled_output)
    print("Fully Connected Layer Output:\n", fc_output)


Convolution Output:
 [[2.2326171  1.62781507 1.94747831]
 [1.35447587 2.14446236 2.79582936]
 [2.51473061 2.85620876 3.12683821]]
ReLU Output:
 [[2.2326171  1.62781507 1.94747831]
 [1.35447587 2.14446236 2.79582936]
 [2.51473061 2.85620876 3.12683821]]
Max Pooling Output:
 [[2.2326171]]
Fully Connected Layer Output:
 [1.87402266 2.05056682 1.75830006]
